version: '3.8'

services:

  app:
    build:
      context: ./client
      args:
        - APP_NEXT_PUBLIC_API_URL=${APP_NEXT_PUBLIC_API_URL}
        - APP_NEXT_PUBLIC_TITILER_API_URL=${APP_NEXT_PUBLIC_TITILER_API_URL}
        - APP_NEXT_PUBLIC_MAPBOX_API_TOKEN=${APP_NEXT_PUBLIC_MAPBOX_API_TOKEN}
    env_file: .env
    ports:
      - "${APP_SERVICE_PORT}:3000"
    restart: unless-stopped

  tiler:
    container_name: tiler
    build:
      context: ./tiler
      args:
        - TILER_FOODSCAPES_COG_FILENAME=${TILER_FOODSCAPES_COG_FILENAME}
        - TILER_IRRECOVERABLE_CARBON_COG_FILENAME=${TILER_IRRECOVERABLE_CARBON_COG_FILENAME}
        - TILER_DEPRIVATION_INDEX_COG_FILENAME=${TILER_DEPRIVATION_INDEX_COG_FILENAME}
        - DATA_CORE_COG_SOURCE_URL=${DATA_CORE_COG_SOURCE_URL}
        - DATA_CORE_COG_CHECKSUM=${DATA_CORE_COG_CHECKSUM}
        - DATA_IRRECOVERABLE_CARBON_COG_SOURCE_URL=${DATA_IRRECOVERABLE_CARBON_COG_SOURCE_URL}
        - DATA_IRRECOVERABLE_CARBON_COG_CHECKSUM=${DATA_IRRECOVERABLE_CARBON_COG_CHECKSUM}
        - DATA_DEPRIVATION_INDEX_COG_SOURCE_URL=${DATA_DEPRIVATION_INDEX_COG_SOURCE_URL}
        - DATA_DEPRIVATION_INDEX_COG_CHECKSUM=${DATA_DEPRIVATION_INDEX_COG_CHECKSUM}
    env_file: .env
    ports:
      - "${TILER_SERVICE_PORT}:3000"
    volumes:
      - ./tiler/data:/opt/foodscapes-tiler/data/local-dev
    restart: unless-stopped

  datasette:
    container_name: datasette
    build:
      context: ./datasette
      args:
        - DATASETTE_SQLITE_DB_FILENAME=${DATASETTE_SQLITE_DB_FILENAME:-foodscapes.db}
        - DATA_CORE_SQLITE_DB_SOURCE_URL=${DATA_CORE_SQLITE_DB_SOURCE_URL}
        - DATA_CORE_SQLITE_DB_CHECKSUM=${DATA_CORE_SQLITE_DB_CHECKSUM}
        - DATASETTE_CORS_ORIGINS=${DATASETTE_CORS_ORIGINS}
    env_file: .env
    ports:
      - "${DATASETTE_SERVICE_PORT}:3000"
    volumes:
      - ./datasette/data:/opt/foodscapes-datasette/data/local-dev
    restart: unless-stopped
