/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { stepAtom } from 'store/home';

import { useGLTF } from '@react-three/drei';
import { motion } from 'framer-motion-3d';
import { useRecoilValue } from 'recoil';

import { GLTFResult } from '../types';

export function Model() {
  const { nodes } = useGLTF('/models/city-3.glb') as GLTFResult;
  const step = useRecoilValue(stepAtom);

  return (
    <mesh
      geometry={nodes.Physical.geometry}
      position={[0, 0.005, 0]}
      scale={0.9742}
      castShadow
      receiveShadow
    >
      <motion.meshStandardMaterial
        animate={`step${step}`}
        variants={{
          initial: { color: '#FFF' },
          step0: { color: '#FFF' },
          step1: { color: '#38661F' },
          step2: { color: '#FFF' },
          step3: { color: '#FFF' },
          step4: { color: '#38661F' },
        }}
      />
    </mesh>
  );
}

useGLTF.preload('/models/city-3.glb');

export default Model;
