/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei';

import { GLTFResult } from '../types';

export function Model() {
  const { nodes } = useGLTF('/models/city-3.glb') as GLTFResult;

  return (
    <mesh
      geometry={nodes.Physical.geometry}
      position={[0, 0.005, 0]}
      scale={0.9742}
      castShadow
      receiveShadow
    >
      <meshStandardMaterial attach="material" color="#38661F" />
      {/* <meshStandardMaterial attach="material" color="#FFF" /> */}
    </mesh>
  );
}

useGLTF.preload('/models/city-3.glb');

export default Model;
