/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei';

import { GLTFResult } from '../types';

export function SocioEconomic() {
  const { nodes } = useGLTF('/models/city-3.glb') as GLTFResult;

  return (
    <mesh
      geometry={nodes.Socioeconomic.geometry}
      position={[-0.3905, 0.2713, -0.8573]}
      rotation={[0, -0.9438, 0]}
      scale={[0.0162, 0.0118, 0.0403]}
      castShadow
    >
      {/* <meshStandardMaterial attach="material" color="#E8CC6B" /> */}
      <meshStandardMaterial attach="material" color="#FFF" />
    </mesh>
  );
}

useGLTF.preload('/models/city-3.glb');

export default SocioEconomic;
