/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei';

import { GLTFResult } from '../types';

export function Management() {
  const { nodes } = useGLTF('/models/city-3.glb') as GLTFResult;

  return (
    <mesh
      geometry={nodes.Management.geometry}
      position={[0.1934, 0.1831, -0.4007]}
      rotation={[0, -0.784, 0]}
      scale={[0.0063, 0.0347, 0.0063]}
      castShadow
    >
      {/* <meshStandardMaterial attach="material" color="#E8856B" /> */}
      <meshStandardMaterial attach="material" color="#FFF" />
    </mesh>
  );
}

useGLTF.preload('/models/city-3.glb');

export default Management;
