/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { Suspense } from 'react';

import { Canvas } from '@react-three/fiber';
import { NoToneMapping } from 'three';

import Camera from './camera';
import Lights from './lights';
import Model from './model';

export function LayerChart() {
  return (
    <Canvas
      camera={{ position: [1, 5, 3], fov: 50 }}
      gl={{
        physicallyCorrectLights: true,
        toneMapping: NoToneMapping,
      }}
      shadows
    >
      <Camera />

      <Lights />

      <Suspense>
        <Model />
      </Suspense>
    </Canvas>
  );
}

export default LayerChart;
