/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei';
import { DoubleSide } from 'three';

import { GLTFResult } from '../types';

export function Water() {
  const { nodes } = useGLTF('/models/city-3.glb') as GLTFResult;

  return (
    <mesh
      geometry={nodes.agua.geometry}
      position={[0.0058, 0.0791, 0.0106]}
      scale={[0.9594, 1.2945, 0.9594]}
      receiveShadow
    >
      <meshStandardMaterial
        attach="material"
        color="#003388"
        transparent
        opacity={0.75}
        side={DoubleSide}
      />
    </mesh>
  );
}

useGLTF.preload('/models/city-3.glb');

export default Water;
