/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { stepAtom } from 'store/home';

import { useGLTF } from '@react-three/drei';
import { useRecoilValue } from 'recoil';
import { DoubleSide } from 'three';

import { STEP_DURATION } from 'containers/home/animations/constants';

import { GLTFResult } from '../types';

export function Water() {
  const { nodes } = useGLTF('/models/city-3.glb') as GLTFResult;
  const step = useRecoilValue(stepAtom);

  return (
    <mesh
      geometry={nodes.agua.geometry}
      position={[0.0058, 0.0791, 0.0106]}
      scale={[0.9594, 1.2945, 0.9594]}
      receiveShadow
    >
      <meshStandardMaterial
        color="#003388"
        transparent
        opacity={0.25}
        side={DoubleSide}
        animate={`step${step}`}
        variants={{
          initial: { opacity: 0.5 },
          step0: { opacity: 0.5 },
          step1: { opacity: 0.5 },
          step2: { opacity: 0.5 },
          step3: { opacity: 0.5 },
          step4: { opacity: 0.5 },
        }}
        transition={{
          duration: STEP_DURATION,
        }}
      />
    </mesh>
  );
}

useGLTF.preload('/models/city-3.glb');

export default Water;
