name: Build and publish container images to GitHub Container Registry

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'staging'
      - 'production'
    paths:
      - 'client/**'
      - 'datasette/**'
      - 'tiler/**'
      - '.github/**'
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  push_tiler_to_registry:
    name: Push tiler container image to registry
    runs-on: ubuntu-22.04
    env:
      REPOSITORY: tiler
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch ids
        shell: bash
        run: |
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
          echo "shortsha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build container image
        env:
          IMAGE_TAG: ${{ steps.extract_branch.outputs.shortsha }}
        run: |
          docker build \
          --build-arg TILER_FOODSCAPES_COG_FILENAME=${{ env.TILER_FOODSCAPES_COG_FILENAME }} \
          --build-arg DATA_CORE_COG_SOURCE_URL=${{ env.DATA_CORE_COG_SOURCE_URL }} \
          --build-arg DATA_CORE_COG_CHECKSUM=${{ env.DATA_CORE_COG_CHECKSUM }} \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG $REPOSITORY

      - name: Push container image to registry
        env:
          IMAGE_TAG: ${{ steps.extract_branch.outputs.shortsha }}
        run: |
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  push_client_to_registry:
    name: Push client container image to registry
    runs-on: ubuntu-22.04
    env:
      REPOSITORY: client
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch ids
        shell: bash
        run: |
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
          echo "shortsha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build container image
        env:
          IMAGE_TAG: ${{ steps.extract_branch.outputs.shortsha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG $REPOSITORY

      - name: Push container image to registry
        env:
          IMAGE_TAG: ${{ steps.extract_branch.outputs.shortsha }}
        run: |
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  push_datasette_to_registry:
    name: Push datasette container image to registry
    runs-on: ubuntu-22.04
    env:
      REPOSITORY: datasette
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch ids
        shell: bash
        run: |
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
          echo "shortsha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build container image
        env:
          IMAGE_TAG: ${{ steps.extract_branch.outputs.shortsha }}
        run: |
          docker build \
          --build-arg DATASETTE_SQLITE_DB_FILENAME=${{ env.DATASETTE_SQLITE_DB_FILENAME }} \
          --build-arg DATA_CORE_SQLITE_DB_SOURCE_URL=${{ env.DATA_CORE_SQLITE_DB_SOURCE_URL }} \
          --build-arg DATA_CORE_SQLITE_DB_CHECKSUM=${{ env.DATA_CORE_SQLITE_DB_CHECKSUM }} \
          --build-arg DATASETTE_CORS_ORIGINS=${{ env.DATASETTE_CORS_ORIGINS }} \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG $REPOSITORY

      - name: Push container image to registry
        env:
          IMAGE_TAG: ${{ steps.extract_branch.outputs.shortsha }}
        run: |
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
